[project]
name = "ai-beta-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.10.1",
    "huggingface-hub>=0.34.4",
    "numpy>=2.3.2",
    "torch>=2.8.0",
    "transformers>=4.56.0",
]
